const titles={upload:["Raw Excel Upload","Sample raw data paste/edit karke pivot preview dekhein."],remarks:["Remarks","Plant + Storage Location wise remarks maintain karein."],manual:["Manual Material Add","Extra material rows raw data me append hongi."],block:["Material Block","Report me skip hone wale materials."],category:["Category Update","Material category helper table."],bakal:["Bakal Plan","Future working table."],tolagaon:["Tolagaon Plan","Future working table."],reports:["HO Stock Report","Pivot Sheet preview available."]};let lastPivot=[];

function showPage(pageId,btn){document.querySelectorAll('.page').forEach(p=>p.classList.remove('active'));document.getElementById(pageId).classList.add('active');document.querySelectorAll('.nav button').forEach(b=>b.classList.remove('active'));btn.classList.add('active');document.getElementById('pageTitle').innerText=titles[pageId][0];document.getElementById('pageSubtitle').innerText=titles[pageId][1];refreshCounts()}
function showReportTab(tabId,btn){document.querySelectorAll('.report-tab-content').forEach(t=>t.classList.remove('active'));document.getElementById(tabId).classList.add('active');document.querySelectorAll('.report-tabs .tab').forEach(b=>b.classList.remove('active'));btn.classList.add('active')}
function demoMessage(text){alert(text)}
function deleteRow(button){button.closest('tr').remove();refreshCounts()}

function addCells(tr, vals){vals.forEach(v=>{const td=document.createElement('td');const inp=document.createElement('input');inp.value=v||'';td.appendChild(inp);tr.appendChild(td)});const td=document.createElement('td');const b=document.createElement('button');b.className='delete-btn';b.innerText='Delete';b.onclick=()=>deleteRow(b);td.appendChild(b);tr.appendChild(td)}
function addRawRow(){const tr=document.createElement('tr');addCells(tr,['','','','','0','','']);document.querySelector('#rawTable tbody').appendChild(tr);refreshCounts()}
function addManualRow(){const tr=document.createElement('tr');addCells(tr,['','','','','0','','']);document.querySelector('#manualTable tbody').appendChild(tr);refreshCounts()}
function addRemarksRow(){const tr=document.createElement('tr');addCells(tr,['','','']);document.querySelector('#remarksTable tbody').appendChild(tr);refreshCounts()}
function addBlockRow(){const tr=document.createElement('tr');addCells(tr,['','']);document.querySelector('#blockTable tbody').appendChild(tr);refreshCounts()}

function readTable(id, cols){const rows=[];document.querySelectorAll('#'+id+' tbody tr').forEach(tr=>{const inputs=[...tr.querySelectorAll('input')];const obj={};cols.forEach((c,i)=>obj[c]=(inputs[i]?.value||'').trim());const has=Object.values(obj).some(v=>v!=='');if(has)rows.push(obj)});return rows}
function key(p,l){return String(p||'')+'||'+String(l||'')}
function readAllData(){const cols=['Plant','Storage Location','Material','Material Description','Unrestricted','Transit and Transfer','Batch'];return [...readTable('rawTable',cols),...readTable('manualTable',cols)]}
function readRemarks(){const rows=readTable('remarksTable',['Plant','Storage Location','Remarks']);const map=new Map();rows.forEach(r=>map.set(key(r['Plant'],r['Storage Location']),r['Remarks']));return {rows,map}}
function readBlockSet(){const rows=readTable('blockTable',['Material','Material Description']);const set=new Set();rows.forEach(r=>{if(r.Material)set.add(String(r.Material).trim())});return {rows,set}}

function syncRemarks(){const data=readAllData();const existing=readRemarks().map;const tbody=document.querySelector('#remarksTable tbody');let added=0;data.forEach(r=>{const k=key(r.Plant,r['Storage Location']);if(!existing.has(k)){const tr=document.createElement('tr');addCells(tr,[r.Plant,r['Storage Location'],'']);tbody.appendChild(tr);existing.set(k,'');added++}});alert(added+' new Plant/Storage rows added in Remarks.');refreshCounts()}

function refreshCounts(){const raw=readTable('rawTable',['Plant','Storage Location','Material','Material Description','Unrestricted','Transit and Transfer','Batch']);const manual=readTable('manualTable',['Plant','Storage Location','Material','Material Description','Unrestricted','Transit and Transfer','Batch']);const remarks=readRemarks();const block=readBlockSet();const combined=[...raw,...manual];let pending=0;const seen=new Set();combined.forEach(r=>{const k=key(r.Plant,r['Storage Location']);if(!seen.has(k)){seen.add(k);const rem=remarks.map.get(k);if(rem===undefined||rem.trim()==='')pending++}});document.getElementById('rawCount').innerText=raw.length;document.getElementById('manualCount').innerText=manual.length;document.getElementById('workingCount').innerText=combined.length;document.getElementById('pendingRemarks').innerText=pending;document.getElementById('blockCount').innerText=block.rows.length;document.getElementById('categoryCount').innerText=0}

function generatePivot(){refreshCounts();const data=readAllData();const remarks=readRemarks().map;const block=readBlockSet().set;const filtered=[];let excludedDelete=0, excludedBlock=0, missing=0;
data.forEach(r=>{const material=String(r.Material||'').trim();if(block.has(material)){excludedBlock++;return}const rem=(remarks.get(key(r.Plant,r['Storage Location']))||'').trim();if(!rem){missing++;return}if(rem.toLowerCase()==='delete'){excludedDelete++;return}filtered.push({...r,Remarks:rem,UnrestrictedNum:Number(r.Unrestricted)||0})});
const remarkCols=[...new Set(filtered.map(r=>r.Remarks))].sort();const pivotMap=new Map();
filtered.forEach(r=>{const k=String(r.Material)+'||'+String(r['Material Description']);if(!pivotMap.has(k)){pivotMap.set(k,{Material:r.Material,'Material Description':r['Material Description']})}const obj=pivotMap.get(k);obj[r.Remarks]=(obj[r.Remarks]||0)+r.UnrestrictedNum});
lastPivot=[...pivotMap.values()].sort((a,b)=>String(a.Material).localeCompare(String(b.Material)));
renderPivot(lastPivot,remarkCols);
document.getElementById('pivotInfo').innerText=`Pivot ready: ${lastPivot.length} materials | ${filtered.length} rows used | ${excludedDelete} delete-remarks rows skipped | ${excludedBlock} blocked-material rows skipped | ${missing} missing-remarks rows skipped`;
}
function renderPivot(rows,remarkCols){const table=document.getElementById('pivotTable');const thead=table.querySelector('thead');const tbody=table.querySelector('tbody');thead.innerHTML='';tbody.innerHTML='';const hr=document.createElement('tr');['Material','Material Description',...remarkCols].forEach(h=>{const th=document.createElement('th');th.innerText=h;hr.appendChild(th)});thead.appendChild(hr);rows.forEach(r=>{const tr=document.createElement('tr');['Material','Material Description',...remarkCols].forEach(c=>{const td=document.createElement('td');td.innerText=(r[c]!==undefined?r[c]:'');tr.appendChild(td)});tbody.appendChild(tr)})}
function downloadPivotCsv(){if(!lastPivot.length){alert('Pehle Generate Pivot Preview dabayein.');return}const headers=[...document.querySelectorAll('#pivotTable thead th')].map(th=>th.innerText);const lines=[headers.join(',')];lastPivot.forEach(r=>{lines.push(headers.map(h=>`"${String(r[h]??'').replaceAll('"','""')}"`).join(','))});const blob=new Blob([lines.join('\n')],{type:'text/csv'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='pivot_sheet_preview.csv';a.click()}
document.addEventListener('input',()=>refreshCounts());refreshCounts();